# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_login(object):
    def setupUi(self, Form_login):
        Form_login.setObjectName("Form_login")
        Form_login.resize(320, 200)
        Form_login.setMinimumSize(QtCore.QSize(320, 200))
        Form_login.setMaximumSize(QtCore.QSize(320, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/login.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form_login.setWindowIcon(icon)
        Form_login.setStyleSheet("font-weight: 400; font-size: 24px; line-height: 24px; color: #000000;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_login)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lbl_usr = QtWidgets.QLabel(Form_login)
        self.lbl_usr.setObjectName("lbl_usr")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_usr)
        self.lineEdit_usr = QtWidgets.QLineEdit(Form_login)
        self.lineEdit_usr.setObjectName("lineEdit_usr")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_usr)
        self.lbl_psw = QtWidgets.QLabel(Form_login)
        self.lbl_psw.setObjectName("lbl_psw")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_psw)
        self.lineEdit_psw = QtWidgets.QLineEdit(Form_login)
        self.lineEdit_psw.setObjectName("lineEdit_psw")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_psw)
        self.lbl_login_error = QtWidgets.QLabel(Form_login)
        self.lbl_login_error.setText("")
        self.lbl_login_error.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_login_error.setObjectName("lbl_login_error")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.lbl_login_error)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.btn_login = QtWidgets.QPushButton(Form_login)
        self.btn_login.setObjectName("btn_login")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.btn_login)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(Form_login)
        QtCore.QMetaObject.connectSlotsByName(Form_login)

    def retranslateUi(self, Form_login):
        _translate = QtCore.QCoreApplication.translate
        Form_login.setWindowTitle(_translate("Form_login", "Login form"))
        self.lbl_usr.setText(_translate("Form_login", "Username:"))
        self.lbl_psw.setText(_translate("Form_login", "Password:"))
        self.btn_login.setText(_translate("Form_login", "Login"))
