# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_open(object):
    def setupUi(self, Form_open):
        Form_open.setObjectName("Form_open")
        Form_open.resize(400, 500)
        Form_open.setMinimumSize(QtCore.QSize(400, 500))
        Form_open.setMaximumSize(QtCore.QSize(400, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form_open.setWindowIcon(icon)
        Form_open.setStyleSheet("font-weight: 400; font-size: 24px; line-height: 24px; color: #000000;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form_open)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_search = QtWidgets.QLineEdit(Form_open)
        self.lineEdit_search.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_search.setStyleSheet("color: #808080;")
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout.addWidget(self.lineEdit_search)
        self.btn_search = QtWidgets.QPushButton(Form_open)
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout.addWidget(self.btn_search)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(Form_open)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.lbl_error = QtWidgets.QLabel(Form_open)
        self.lbl_error.setText("")
        self.lbl_error.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_error.setObjectName("lbl_error")
        self.verticalLayout_2.addWidget(self.lbl_error)
        self.btn_choose = QtWidgets.QPushButton(Form_open)
        self.btn_choose.setObjectName("btn_choose")
        self.verticalLayout_2.addWidget(self.btn_choose)

        self.retranslateUi(Form_open)
        QtCore.QMetaObject.connectSlotsByName(Form_open)

    def retranslateUi(self, Form_open):
        _translate = QtCore.QCoreApplication.translate
        Form_open.setWindowTitle(_translate("Form_open", "Open"))
        self.lineEdit_search.setText(_translate("Form_open", "Введите имя"))
        self.btn_search.setText(_translate("Form_open", "Поиск"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form_open", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form_open", "Имя"))
        self.btn_choose.setText(_translate("Form_open", "Выбрать"))
