# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'record.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_record(object):
    def setupUi(self, Form_record):
        Form_record.setObjectName("Form_record")
        Form_record.resize(800, 600)
        Form_record.setMinimumSize(QtCore.QSize(800, 600))
        Form_record.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/record.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form_record.setWindowIcon(icon)
        Form_record.setStyleSheet("font-weight: 400; font-size: 24px; line-height: 24px; color: #000000;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_record)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_img = QtWidgets.QLabel(Form_record)
        self.lbl_img.setText("")
        self.lbl_img.setPixmap(QtGui.QPixmap("img/raskladka.jpg"))
        self.lbl_img.setScaledContents(True)
        self.lbl_img.setObjectName("lbl_img")
        self.verticalLayout.addWidget(self.lbl_img)
        self.lbl_1 = QtWidgets.QLabel(Form_record)
        self.lbl_1.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lbl_1.setObjectName("lbl_1")
        self.verticalLayout.addWidget(self.lbl_1)
        self.lbl_2 = QtWidgets.QLabel(Form_record)
        self.lbl_2.setObjectName("lbl_2")
        self.verticalLayout.addWidget(self.lbl_2)
        self.label = QtWidgets.QLabel(Form_record)
        self.label.setStyleSheet("color: red;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(Form_record)
        QtCore.QMetaObject.connectSlotsByName(Form_record)

    def retranslateUi(self, Form_record):
        _translate = QtCore.QCoreApplication.translate
        Form_record.setWindowTitle(_translate("Form_record", "Record"))
        self.lbl_1.setText(_translate("Form_record", "Ноты записываются при нажатии на клавиши, находящиеся внутри"))
        self.lbl_2.setText(_translate("Form_record", "красного многоугольника"))
        self.label.setText(_translate("Form_record", "Чтобы закончить запись нажмите \"Esc\""))
