# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saving.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_save(object):
    def setupUi(self, Form_save):
        Form_save.setObjectName("Form_save")
        Form_save.resize(320, 200)
        Form_save.setMinimumSize(QtCore.QSize(320, 200))
        Form_save.setMaximumSize(QtCore.QSize(320, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form_save.setWindowIcon(icon)
        Form_save.setStyleSheet("font-weight: 400; font-size: 24px; line-height: 24px; color: #000000;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form_save)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_name = QtWidgets.QLabel(Form_save)
        self.lbl_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_name.setObjectName("lbl_name")
        self.verticalLayout.addWidget(self.lbl_name)
        self.lineEdit_name = QtWidgets.QLineEdit(Form_save)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.verticalLayout.addWidget(self.lineEdit_name)
        self.lbl_saving_error = QtWidgets.QLabel(Form_save)
        self.lbl_saving_error.setText("")
        self.lbl_saving_error.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_saving_error.setObjectName("lbl_saving_error")
        self.verticalLayout.addWidget(self.lbl_saving_error)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_cansel = QtWidgets.QPushButton(Form_save)
        self.btn_cansel.setObjectName("btn_cansel")
        self.horizontalLayout.addWidget(self.btn_cansel)
        self.btn_save = QtWidgets.QPushButton(Form_save)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form_save)
        QtCore.QMetaObject.connectSlotsByName(Form_save)

    def retranslateUi(self, Form_save):
        _translate = QtCore.QCoreApplication.translate
        Form_save.setWindowTitle(_translate("Form_save", "Saving"))
        self.lbl_name.setText(_translate("Form_save", "Имя мелодии:"))
        self.btn_cansel.setText(_translate("Form_save", "Отмена"))
        self.btn_save.setText(_translate("Form_save", "Сохранить"))
